---
title: Declaración Pública
subtitle: "Uso de compuestos químicos por Carabineros de Chile"
author: "Asamblea por el Conocimiento y la Investigación"
date: "17/12/2019"
output:
  tufte::tufte_html:
    css: "parche.css"
  tufte::tufte_handout: default
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

Desde que el estallido social comenzó 18 de octubre, hemos sido testigos del uso indiscriminado de disuasivos químicos para el mantenimiento del orden público en todo Chile. Aun considerando que el uso de estos gases está extendido en todo el mundo, hay evidencia suficiente para considerar que representan una amenaza real para la salud humana. Además, uno de los grandes problemas de los disuasivos químicos, es que, una vez empleados, se propagan rápidamente por efectos ambientales (viento, temperatura, humedad) afectando no solo al grupo a disuadir sino también a la comunidad aledaña.

En la legislación internacional estos compuestos, en principio no letales, son considerados como armas químicas y por lo tanto su uso está prohibido en conflictos bélicos.[^1] A pesar de esto, su uso está permitido para controlar conflictos o manifestaciones sociales, aunque con protocolos bien establecidos que incluyen la prohibición de usarlos en recintos cerrados y la obligación de advertir previamente a los manifestantes. En tanto, la Comisión Interamericana de Derechos Humanos[^2] agrega que deben existir prohibiciones taxativas de uso en contextos que puedan implicar riesgos mayores, como por ejemplo, no deben ser utilizados frente a personas que no tienen una vía de desconcentración o evacuación.

El protocolo de Carabineros para uso de estos gases[^3], que fue elaborado sin la participación de las instituciones nacionales encargadas de velar por los DDHH[^4], en principio se hace cargo de estas prevenciones. Sin embargo múltiples evidencias indican que el uso de estos compuestos no siempre se ajusta a este protocolo. Por ejemplo, se han disparado bombas lacrimógenas mediante escopetas, directamente sobre el cuerpo de personas a pocos metros de distancia, dejando heridos de gravedad; y han sido usados contra personas que se manifiestan pacíficamente sin mediar aviso previo. Además se ha incurrido en otras faltas, no consideradas en el protocolo mencionado, como disparar lacrimógenas en recintos cerrados, tal como departamentos, autos en movimento, casas, colegios, hospitales y otros centros de uso comunitario. Cabe mencionar que las granadas manuales necesitan altas temperaturas para dispersar el compuesto activo (&gt;700°C) por lo que las chispas generadas en el proceso pueden además producir incendios o causar quemaduras graves a personas y animales. Sobre todos estos hechos existen denuncias del [parlamento](https://www.cooperativa.cl/noticias/pais/educacion/colegios/proyecto-de-ley-busca-prohibir-utilizacion-de-gas-lacrimogeno-en/2019-09-12/033319.html) nacional, de la Defensoría de la Niñez, del Colegio Médico de Chile, y de las organizaciones internacionales de DDHH [Human Right Watch](https://www.hrw.org/es/news/2019/11/26/chile-llamado-urgente-una-reforma-policial-tras-las-protestas) y [Amnistía Internacional](https://www.amnesty.org/es/latest/news/2019/11/chile-responsable-politica-deliberada-para-danar-manifestantes/).

Respecto a los compuestos químicos usados, a partir de declaraciones de funcionarios policiales y de informes previos sobre el tema [^5][^6], es seguro que Carabineros de Chile usa al menos dos compuestos químicos como agentes disuasivos: 2-clorobenzilideno malononitrilo (CS) y Oleoresin capsicum (OC o gas pimienta). El CS es el principal agente lacrimógeno usado[^7] en el mundo y según declaraciones del general de Carabineros Jorge Ávila es el compuesto disuelto en el agua del carro lanzagua.[^8] La literatura indica que este compuesto, así como el 2-cloroacetofenona (CN) y el dibenz[b,f]-1:4-oxazepina (CR) son los principales compuestos lacrimógenos dispersados mediante escopetas, granadas de mano y carros lanzagases.^6,10^

El objetivo de estos compuestos es producir una discapacidad temporal, producto de la irritación y el dolor en las zonas afectadas, principalmente mucosas expuestas como ojos, tractos digestivo y respiratorio.[^9] Se caracterizan por producir su efecto de manera inmediata, consiguiendo el objetivo de dispersar manifestaciones, cuando otros métodos no letales no lo consiguen. Sin embargo, existen dudas razonables sobre los posibles efectos a mediano y largo plazo en la salud de las personas expuestas, que no han sido estudiados de manera profunda. Igualmente existen dudas sobre el efecto de estos compuestos en altas concentraciones, dado que el protocolo de Carabineros no trata este tema. Por último existe preocupación por registros fotográficos de granadas lacrimógenas usadas, que estaban vencidas hace varios años. Todas estas preocupaciones sustentadas además por evidencia de daños y muertes asociadas a su uso en todo el mundo.[^10]

Algunas preocupaciones específicas respecto a la salud, relacionadas con estos compuestos son las siguientes:

- El efecto irritante de los compuestos CS, CR, CN y OC en las mucosas oculares, de los tractos respiratorio y digestivo, es especialmente peligroso en personas de la tercera edad, niñas y niños, personas con enfermedades respiratorias y mujeres embarazadas.[^11] CS y CR además pueden producir daños pulmonares si se administran en altas concentraciones, e incluso producir la muerte por esta causa^6^.
- Los compuestos mencionados aumentan la ansiedad y el pánico, lo que genera un estrés del sistema cardiorespiratorio, generando síntomas como taquicardia y aumento de la presión arterial. Esto es especialmente grave cuando estos gases son usados en ambientes cerrados o con poca ventilación, o los afectados tienen problemas cardiovasculares.[^12]
- Tanto CN como CS pueden producir daños en la piel, pasando de la inflamación y el enrojecimiento a quemaduras de grado II o III (necrosis del tejido dérmico) al ser usados en altas concentraciones y/o por tiempos prolongados.^6^
- Las formulaciones de CS son persistentes y pueden llegar a estar activas por 5 días en el ambiente luego de ser usado. Cualquier acción mecánica sobre el suelo (barrer, caminar, tráfico vehícular) puede volver a suspender este polvo en el aire y por tanto volver a activar sus efectos.[^13]
- Durante la liberación pirogénica de CS (granadas de mano) se liberan gases extremadamente tóxicos como ácido clorhídrico (HCl) y cianuro de hidrógeno (HCN) que pueden causar intoxicación aguda o incluso ser mortales en ambientes cerrados.[^14]

Además de las preocupaciones por el mal uso de los compuestos descritos, existen reportes que sugieren el uso de otro tipo de gases.[^15] Testigos dicen haber visto gases tanto amarillos como verdosos lanzados por Carabineros en algunos sectores de Santiago. Personas expuestas a estos gases dicen sentir irritación, mareos y náuseas explosivas que duran varias horas o incluso días. Los colores y los síntomas denunciados sugieren que se está usado el peligroso agente vomitivo adamsita (DM). Este compuesto se usó durante el siglo XX como agente de mantenimiento del orden, pero cayó en desuso dada su alta toxicidad. Sin embargo, hay reportes no oficiales de su uso en Venezuela entre 2014 y 2017, con características y efectos similares a los vistos en Chile.

Hasta ahora, frente a las solicitudes de información por Ley de Transparencia sobre estos compuestos y los productos usados para aplicarlos, Carabineros de Chile se ha negado a responder[^16], esgrimiendo que se “produciría un daño o detrimento en el debido cumplimiento de las funciones de Carabineros, particularmente en materias de restablecimiento del orden público”. Sin embargo, en 2016 luego de un año de judicializado el caso, Carabineros solo entregó información sobre gasto, licitaciones y registro de proveedores, pero sin dar cuenta del volumen y características específicas de los referidos elementos disuasivos.

Finalmente, frente a este conjunto de preocupaciones sobre la salud planteadas y respaldadas ampliamente por evidencia científica, frente a la evidencia de mal uso de estos compuestos químicos por parte de Carabineros de Chile y a la falta de información oficial sobre estos mismos compuestos, los miembros de los abajo firmantes venimos a exigir:

1. Que el Ministerio del Interior y Carabineros de Chile informe de manera transparente los distintos tipos de compuestos químicos utilizados según el mecanismo de disgregación, su origen y ficha técnica, teniendo un estricto control de inventario, con trazabilidad de cada elemento, supervisado por un organismo externo como el Instituto de Salud Pública u otra entidad pública independiente.
2. Que Carabineros de Chile permita la toma de muestras aleatorias de los distintos productos utilizados para su análisis por Universidades y/o Centros nacionales que tengan la capacidad de llevarlos a cabo. Los resultados de estas investigaciones deben hacerse públicos. Esto debe incluir agua de carros lanzaaguas. 
3. Que los protocolos de uso de estos compuestos se revisen para prohibir su uso en lugares cercanos a recintos de salud y educacionales, así como zonas residenciales. Esta revisión debe hacerse en conjunto con las instituciones de DDHH, de salud e investigación científica pertinentes. 
4. Que el Ministerio del Interior en conjunto con Carabineros de Chile establezca procedimientos transparentes para capacitar a los funcionarios policiales en el uso de estos compuestos, así como establecer sanciones claras toda vez que estos protocolos no sean respetados. 

Finalmente el Estado Chileno representado por este gobierno es el responsable de los daños ocurridos a las personas y animales, por el uso de elementos disuasivos, fuera todos los convenios y protocolos firmados para garantizar el respeto a los derechos humanos.

$~$

Firman,

- Asamblea por el Conocimiento y la Investigación Chile 
- Bloque Salud Unidad Social 
- Colegio Chileno de Químicos A.G.
- Asociación Red de Investigadoras
- Asociación Nacional de Investigadores en Postgrado (ANIP)
- Asamblea de Postgrado UChile
- Frente Conocimiento

(Para firmas institucionales comunicarse a [contacto@acic.cl](mailto:contacto@acic.cl))

<center>
# [Firmar declaración](https://forms.gle/DpG124aZn4TnDdot7)
</center>

$~$

[^1]: Convención sobre las Armas Químicas. Organización para la Prohibición de las Armas Químicas (1997). [Link](https://www.opcw.org/es/convencion-sobre-las-armas-quimicas)

[^2]: Comisión Interamericana de Derechos Humanos. Informe Anual 2015 - Capítulo IV, Uso de la Fuerza. OEA/Ser.L/V/II.Doc. 48/15 (2015). [Link](http://www.oas.org/es/cidh/docs/anual/2015/doc-es/InformeAnual2015-cap4A-fuerza-ES.pdf)

[^3]: D. G. Carabineros de Chile, “Protocolo orden público, orden general N°2635, Carabineros de Chile.” Santiago. Chile. (2019) [Link](https://www.diariooficial.interior.gob.cl/publicaciones/2019/03/04/42295/01/1556120.pdf)

[^4]: INDH y Defensoría de la Niñez critican nuevo protocolo de uso de la fuerza de Carabineros. Economía y Negocios Online. Publicado el 05 de marzo de 2019. [Link](http://www.economiaynegocios.cl/noticias/noticias.asp?id=551407)

[^5]: Abujatum JS. Normativa internacional sobre el uso de gases lacrimógenos y sus compuestos químicos. Biblioteca del Congreso Nacional de Chile. (2019). [Link](https://www.bcn.cl/obtienearchivo?id=repositorio/10221/27644/1/Normativa_internacional_sobre_el_uso_de_gases_lacrimogenos.pdf)

[^6]: Muñoz León, F. El uso de gases lacrimógenos en chile: normativa internacional y nacional vigente y jurisprudencia reciente. Estudios constitucionales 14(1). (2016) [Link](https://scielo.conicyt.cl/scielo.php?script=sci_arttext&pid=S0718-52002016000100007&lng=en&nrm=iso&tlng=en)

[^7]: Olajos EJ, Stopford W, editors. Riot Control Agents: Issues in Toxicology, Safety and Health. CRC Press. (2004)

[^8]: Sesión del 9 de Diciembre de 2019 de la Comisión de DDHH del Senado de Chile. [Link](https://tv.senado.cl/tvsenado/comisiones/permanentes/derechos-humanos/comision-de-derechos-humanos/2019-12-09/142004.html)

[^9]: Encalada D, Estay S, Estrada S, Fuentes P, Leiva J, Mandiola MI, Martínez D, Olguín P, Sánchez L, Tepper A, Vargas A, Villanueva V, Vivaceta A. Informe acerca del uso de gases lacrimógenos por agentes del Estado. Universidad de Valparaíso. (2019)

[^10]: Haar RJ, Iacopino V, Ranadive N, Weiser SD, Dandu M. Health impacts of chemical irritants used for crowd control: a systematic review of the injuries and deaths caused by tear gas and pepper spray. BMC Public Health 17, 831 (2017).

[^11]:  Blain PG. Tear gases and irritant incapacitants. 1-chloroacetophenone, 2-chlorobenzylidene malononitrile and dibenz[b,f]-1,4-oxazepine. Toxicol Rev 22(2), 103-10. (2003).

[^12]:  Rothenberg C, Achanta S, Svendsen ER, Jordt SE. Tear gas: an epidemiological and mechanistic reassessment. Ann N Y Acad Sci. 1378(1), 96-107. (2016)

[^13]:  Organización Mundial de la Salud. Respuesta de la Salud Pública a las Armas Biológicas y Químicas - Guía de la WHO - Segunda Edición (2003)

[^14]:  Kluchinsky TA Jr, Savage PB, Fitz R, Smith PA. Liberation of hydrogen cyanide and hydrogen chloride during high-temperature dispersion of CS riot control agent. AIHA J (Fairfax, Va). 63(4), 493-6. (2002)

[^15]:  Denuncian sustancia extraña en gas lacrimógeno: Provocaría vómitos y tendría otro color. 24 horas. Publicado el 23 de noviembre de 2019. [Link](https://www.24horas.cl/nacional/denuncian-sustancia-extrana-en-gas-lacrimogeno-provocaria-vomitos-y-tendria-otro-color-3747342) 

[^16]:  Millonario gasto de Carabineros en lacrimógenas: los peligros y el protocolo para gasear. Radio BioBio. Publicado el 21 octubre de 2017. [Link](https://www.biobiochile.cl/noticias/nacional/chile/2017/10/21/millonario-gasto-de-carabineros-en-lacrimogenas-los-peligros-y-el-protocolo-para-gasear.shtml)
